#!/bin/bash

export distribution=$(lsb_release -is)
export release=$(lsb_release -rs)
export codename=$(lsb_release -cs)

function whiptail_rtorrent() {
	if [[ -z $rtorrentver ]] && [[ -z $1 ]] && [[ -z $RTORRENT_VERSION ]]; then
        repov=$(get_candidate_version rtorrent)

        whiptail --title "rTorrent Install Advisory" --msgbox "We recommend rTorrent version selection instead of repo (distro) releases. They will compile additional performance and stability improvements in 90s. UDNS includes a stability patch for UDP trackers on rTorrent." 15 50

        function=$(whiptail --title "Choose an rTorrent version" --menu "All versions other than repo will be locally compiled from source" --ok-button "Continue" 14 50 5 \
            0.15.3 "(UDNS)" \
            stickz "(0.9.8-stickz)" 3>&1 1>&2 2>&3) || {
            echo_error "rTorrent version choice aborted"
            exit 1
        }

        set_rtorrent_version $function
    elif [[ -n $RTORRENT_VERSION ]]; then
        set_rtorrent_version $RTORRENT_VERSION
    fi
}

function set_rtorrent_version() {
	case $1 in
        stickz | 'stickz')
            export rtorrentver='0.9.8-stickz'
            export libtorrentver='0.13.8-stickz'
            export libudns='true'
            ;;
	
        0.15.3 | '0.15.3')
            export rtorrentver='0.15.3'
            export libtorrentver='0.15.3'
            export libudns='false'
            ;;

        *)
            echo_error "$1 is not a valid rTorrent version"
            exit 1
            ;;
    esac
}

function configure_rtorrent() {
    # Link time optimizations for 4 plus threads
    if [ $(nproc) -ge 4 ]; then
        export rtorrentflto="-flto=$(nproc)"
    else
        export rtorrentflto=""
    fi
    # pipe optimizations for 512MB plus memory
    memory=$(awk '/MemAvailable/ {printf( "%.f\n", $2 / 1024 )}' /proc/meminfo)
    if [[ $memory > 512 ]]; then
        export rtorrentpipe="-pipe"
    else
        export rtorrentpipe=""
    fi
    # GCC optimization level for program compilation
    if [ $(nproc) -le 1 ]; then
        export rtorrentlevel="-O1"
    elif [ $(nproc) -ge 8 ]; then
        export rtorrentlevel="-O3"
    else
        export rtorrentlevel="-O2"
    fi
}

function depends_rtorrent() {
    APT='subversion dos2unix bc screen zip unzip build-essential comerr-dev
    automake libtool libcppunit-dev libssl-dev pkg-config libcurl4-openssl-dev
    libsigc++-2.0-dev libncurses5-dev libtinyxml2-dev mediainfo yasm autoconf-archive'
        apt_install $APT

        . /etc/swizzin/sources/functions/fpm
        install_fpm

    # mktorrent from source
    cd /tmp
    curl -sL https://github.com/Rudde/mktorrent/archive/v1.1.zip -o mktorrent.zip >> $log 2>&1
    . /etc/swizzin/sources/functions/utils
    rm_if_exists "/tmp/mktorrent"
    unzip -d mktorrent -j mktorrent.zip >> $log 2>&1
    cd mktorrent
    make -j$(nproc) CC=gcc CFLAGS="-w ${rtorrentflto} ${rtorrentpipe} ${rtorrentlevel}" >> $log 2>&1
    make install PREFIX=/usr >> $log 2>&1
    cd /tmp
    rm -rf mktorrent*

    # libudns from source
    if [[ ${libudns} == "true" ]]; then
        git clone -q https://github.com/shadowsocks/libudns /tmp/udns >> $log 2>&1
        cd /tmp/udns
        ./autogen.sh >> $log 2>&1
        ./configure --prefix=/usr >> $log 2>&1
        make -j$(nproc) CFLAGS="-w ${rtorrentflto} ${rtorrentpipe} ${rtorrentlevel} -fPIC" >> $log 2>&1
        make -s install >> $log 2>&1
        cd /tmp
        rm -rf udns*
    fi
}

function build_xmlrpc-c() {    
    if [[ ! ${rtorrentver} == "0.15.3" && ! ${rtorrentver} == "0.9.8-stickz" ]]
    fi
}

#function build_xmlrpc-c_old() {
#    cd "/tmp"
#    . /etc/swizzin/sources/functions/utils
#    rm_if_exists "/tmp/xmlrpc-c"
#    rm_if_exists "/tmp/dist/xmlrpc-c "
#    svn checkout svn://svn.code.sf.net/p/xmlrpc-c/code/super_stable /tmp/xmlrpc-c >> $log 2>&1;
#    cd /tmp/xmlrpc-c
#    cp -rf /etc/swizzin/sources/patches/rtorrent/xmlrpc-config.guess config.guess >> $log 2>&1
#    cp -rf /etc/swizzin/sources/patches/rtorrent/xmlrpc-config.sub config.sub >> $log 2>&1
#    ./configure --prefix=/usr --disable-cplusplus --disable-wininet-client --disable-libwww-client --disable-abyss-server --disable-cgi-server >> $log 2>&1 || {
#        echo_error "Something went wrong while configuring xmlrpc"
#        exit 1
#    }
#    source <(sed 's/ //g' version.mk)
#    VERSION=$XMLRPC_MAJOR_RELEASE.$XMLRPC_MINOR_RELEASE.$XMLRPC_POINT_RELEASE
#    make -j$(nproc) CFLAGS="-w ${rtorrentlevel} ${rtorrentflto} ${rtorrentpipe}" >> $log 2>&1
#    make DESTDIR=/tmp/dist/xmlrpc-c install >> $log 2>&1 || {
#        echo_error "Something went wrong while making xmlrpc"
#        exit 1
#    }
#    mkdir -p /root/dist
#    fpm -f -C /tmp/dist/xmlrpc-c -p /root/dist/xmlrpc-c_VERSION.deb -s dir -t deb -n xmlrpc-c --version ${VERSION} --description "xmlrpc-c compiled by swizzin" > /dev/null 2>&1
#    dpkg -i /root/dist/xmlrpc-c_${VERSION}.deb >> $log 2>&1
#    cd /tmp
#    rm -rf xmlrpc-c
#    rm -rf /tmp/dist/xmlrpc-c
#}

function build_libtorrent_rakshasa() {
    if [[ ${libtorrentver} == "0.15.3" ]]; then
        build_libtorrent_rakshasa_new
    else
        install_libtorrent_stickz
    fi
}

function build_libtorrent_rakshasa_new() {
    . /etc/swizzin/sources/functions/utils
    download_libtorrent_rakshasa
    auto_patch_libtorrent_rakshasa

    autoreconf -vfi >> $log 2>&1
    ./configure --prefix=/usr --enable-aligned >> $log 2>&1 || {
        echo_error "Something went wrong while configuring libtorrent"
        exit 1
    }
    make -j$(nproc) CXXFLAGS="-w ${rtorrentlevel} ${rtorrentflto} ${rtorrentpipe}" >> $log 2>&1 || {
        echo_error "Something went wrong while making libtorrent"
        exit 1
    }

    install_libtorrent_rakshasa
}

function download_libtorrent_rakshasa() {
    libtorrentloc="https://github.com/rakshasa/libtorrent/archive/refs/tags/v${libtorrentver}.tar.gz"
    cd "/tmp"
    . /etc/swizzin/sources/functions/utils
    rm_if_exists "/tmp/libtorrent"
    mkdir /tmp/libtorrent
    curl -sL ${libtorrentloc} -o /tmp/libtorrent-${libtorrentver}.tar.gz
    tar -xf /tmp/libtorrent-${libtorrentver}.tar.gz -C /tmp/libtorrent --strip-components=1 >> $log 2>&1
    cd /tmp/libtorrent >> $log 2>&1
}

function auto_patch_libtorrent_rakshasa() {
    . /etc/swizzin/sources/functions/utils
    if [[ -f /root/libtorrent-rakshasa-${libtorrentver}.patch ]]; then
        patch -p1 < /root/libtorrent-rakshasa-${libtorrentver}.patch >> ${log} 2>&1 || {
            echo _error "Something went wrong when patching libtorrent-rakshasa"
            exit 1
        }
        echo_info "Libtorrent-rakshasa patch found and applied!"
    else
        echo_log_only "No libtorrent-rakshasa patch found at /root/libtorrent-rakshasa-${libtorrentver}.patch"
    fi
}

function install_libtorrent_rakshasa() {
    VERSION=$libtorrentver
    . /etc/swizzin/sources/functions/utils
    rm_if_exists "/tmp/dist/libtorrent-rakshasa"
    make DESTDIR=/tmp/dist/libtorrent-rakshasa install >> $log 2>&1
    mkdir -p /root/dist
    fpm -f -C /tmp/dist/libtorrent-rakshasa -p /root/dist/libtorrent-rakshasa_VERSION.deb -s dir -t deb -n libtorrent-rakshasa --version ${VERSION} --description "libtorrent-rakshasa compiled by swizzin" > /dev/null 2>&1
    dpkg -i /root/dist/libtorrent-rakshasa_${VERSION}.deb >> $log 2>&1
    cd /tmp
    rm -rf /tmp/dist/libtorrent-rakshasa
    rm -rf libtorrent*
}

function install_libtorrent_stickz() {
    cd "/tmp" && git clone https://github.com/stickz/rtorrent/
    . /etc/swizzin/sources/functions/utils
    cd /tmp/rtorrent/libtorrent >> $log 2>&1
    ./autogen.sh >> $log 2>&1
    ./configure --prefix=/usr --enable-aligned --enable-hosted-mode --enable-udns >> $log 2>&1 || {
        echo_error "Something went wrong while configuring libtorrent"
        exit 1
    }
    make -j$(nproc) CXXFLAGS="-w ${rtorrentlevel} ${rtorrentflto} ${rtorrentpipe}" >> $log 2>&1 || {
        echo_error "Something went wrong while making libtorrent"
        exit 1
    }
    make install >> $log 2>&1
    cd /tmp
}

function build_rtorrent() {
    if [[ ${rtorrentver} == "0.15.3" ]]; then
        build_rtorrent_new
    else
        install_rtorrent_stickz
    fi
}

function build_rtorrent_new() {
    . /etc/swizzin/sources/functions/utils
    download_rtorrent
    auto_patch_rtorrent

    autoreconf -vfi >> $log 2>&1
    ./configure --prefix=/usr --with-xmlrpc-tinyxml2 >> $log 2>&1 || {
            echo_error "Something went wrong while configuring rtorrent with tinyxml2"
            exit 1
        }
    make -j$(nproc) CXXFLAGS="-w ${rtorrentlevel} ${rtorrentflto} ${rtorrentpipe}" >> $log 2>&1 || {
        echo_error "Something went wrong while making rtorrent"
        exit 1
    }

    install_rtorrent
}

function install_rtorrent_stickz() {
    . /etc/swizzin/sources/functions/utils
    cd /tmp/rtorrent/rtorrent >> $log 2>&1
    ./autogen.sh >> $log 2>&1
    ./configure --prefix=/usr --with-xmlrpc-tinyxml2 >> $log 2>&1 || {
        echo_error "Something went wrong while configuring rtorrent"
        exit 1
    }
    make -j$(nproc) CXXFLAGS="-w ${rtorrentlevel} ${rtorrentflto} ${rtorrentpipe}" >> $log 2>&1 || {
        echo_error "Something went wrong while making rtorrent"
        exit 1
    }
	make install >> $log 2>&1
    apt-mark hold rtorrent >> ${log} 2>&1
    cd /tmp
    rm -rf rtorrent
}

function download_rtorrent() {
    rtorrentloc="https://github.com/rakshasa/rtorrent/archive/refs/tags/v${rtorrentver}.tar.gz"
    cd "/tmp"
    . /etc/swizzin/sources/functions/utils
    rm_if_exists "/tmp/rtorrent*"
    mkdir /tmp/rtorrent
    curl -sL ${rtorrentloc} -o /tmp/rtorrent-${rtorrentver}.tar.gz
    tar -xzf /tmp/rtorrent-${rtorrentver}.tar.gz -C /tmp/rtorrent --strip-components=1 >> $log 2>&1
    cd /tmp/rtorrent
}

function auto_patch_rtorrent() {
    . /etc/swizzin/sources/functions/utils
    if [[ -f /root/rtorrent-${rtorrentver}.patch ]]; then
        patch -p1 < /root/rtorrent-${rtorrentver}.patch >> ${log} 2>&1 || {
            echo _error "Something went wrong when patching rTorrent"
            exit 1
        }
        echo_info "rTorrent patch found and applied!"
    else
        echo_log_only "No rTorrent patch found at /root/rtorrent-${rtorrentver}.patch"
    fi
}

function install_rtorrent() {
    VERSION=$rtorrentver
    . /etc/swizzin/sources/functions/utils
    rm_if_exists "/tmp/dist/rtorrent"
    make DESTDIR=/tmp/dist/rtorrent install >> $log 2>&1
    mkdir -p /root/dist
    fpm -f -C /tmp/dist/rtorrent -p /root/dist/rtorrent_VERSION.deb -s dir -t deb -n rtorrent --version ${VERSION} --description "rtorrent compiled by swizzin" > /dev/null 2>&1
    dpkg -i /root/dist/rtorrent_${VERSION}.deb >> $log 2>&1
    cd "/tmp"
    ldconfig >> $log 2>&1
    rm -rf rtorrent* >> $log 2>&1
    rm -rf /tmp/dist/rtorrent
    apt-mark hold rtorrent >> ${log} 2>&1
}

function rtorrent_apt() {
    apt_install rtorrent
}

function remove_rtorrent() {
    toclean=(rtorrent libtorrent-rakshasa)
    repo=$(dpkg -l | grep -P libtorrent'\d+' | awk '{print $2}' | cut -d: -f1)
    if [[ -n $repo ]]; then
        toclean+=($repo)
    fi
    for c in ${toclean[@]}; do
        # TODO add option to pass extra flags
        apt-get remove -y -q --allow-change-held-packages $c >> $log 2>&1
    done
    apt-get autoremove -y >> $log 2>&1
}

function remove_rtorrent_legacy() {
    rm -rf /usr/bin/rtorrent
    cd /tmp
    git clone https://github.com/rakshasa/libtorrent.git libtorrent >> /dev/null 2>&1
    cd libtorrent
    ./autogen.sh >> $log 2>&1
    ./configure --prefix=/usr >> $log 2>&1
    make uninstall >> $log 2>&1
    cd -
    rm -rf /tmp/libtorrent
}
